---
title: "Protest Analysis"
author: "Arica Schuett"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Libraries

```{r libraries}
library(dplyr)
library(tidyverse)
library(ggplot2)
```

## Import Data

```{r import }
ProtestByCity <- read.csv("/Users/aricaschuett/Documents/protest/ProtestByCity3-25.csv", row.names = NULL)
```

## Replace NAs with 0 in Specific Columns


## Cities with No Protest

```{r no protest cities }
NoProtestCities <- ProtestByCity %>%
  filter(PostGFProtestCount == 0)
write.csv(NoProtestCities, "/Users/aricaschuett/Documents/protest/NoProtestCities3-25.csv")


summary(NoProtestCities$population)
summary(NoProtestCities$BlackPopPct)
summary(NoProtestCities$EduRate)
summary(NoProtestCities$CollegeStudents)
summary(NoProtestCities$AntiTrumpProtestPreGFCount)
summary(NoProtestCities$VictimsCount)

```

## Cities with Protest

```{r protest cities}
ProtestCities <- ProtestByCity %>%
  filter(PostGFProtestCount > 0)
write.csv(ProtestCities, "/Users/aricaschuett/Documents/protest/ProtestCities3-25.csv")

summary(ProtestCities$population)
summary(ProtestCities$BlackPopPct)
summary(ProtestCities$EduRate)
summary(ProtestCities$CollegeStudents)
summary(ProtestCities$AntiTrumpProtestPreGFCount)
summary(ProtestCities$VictimsCount)
```


## Full Linear Models

```{r full models}
m1 <- lm(PostGFProtestCount ~ population , data = ProtestByCity)
nobs(m1) #19749
summary(m1)

m2 <- lm(PostGFProtestCount ~ population + BlackPop + BlackPov + CollegeEdTotal + VictimsPreGF2020, data = ProtestByCity)
nobs(m2) #19749
used_data <- model.frame(m2)
dropped_obs <- anti_join(ProtestByCity, used_data, by = c("PostGFProtestCount","VictimsPreGF2020"))
summary(m2)

m3 <- lm(PostGFProtestCount ~ population + BlackPop + BlackPov + CollegeEdTotal + VictimsPreGF2020, data = ProtestByCity)
nobs(m3) #19749
used_data <- model.frame(m3)
dropped_obs <- anti_join(ProtestByCity, used_data, by = c("PostGFProtestCount","VictimsPreGF2020"))
summary(m3)

m11 <- lm(PostGFProtestCount ~ population + BlackPop + BlackPov + CollegeEdTotal + VictimCountPreGF, data = ProtestByCity)
nobs(m11) #19749
summary(m11)

m12 <- lm(PostGFProtestCount ~ population + BlackPop + BlackPov + CollegeEdTotal + VictimsPreGF2020, data = ProtestByCity)
nobs(m12) #19749
summary(m12)


m13 <- lm(PostGFProtestCount ~ population + BlackPop + BlackPov + CollegeEdTotal + VictimsPreGF2020Blk, data = ProtestByCity)
nobs(m13) #19749
summary(m13)


m14 <- lm(PostGFProtestCount ~ population + BlackPopPct + BlackPovRate + EduRate + VictimCountPreGF, data = ProtestByCity)
nobs(m14) #19749
summary(m14)

```

## Place with No Black People
```{r sample models}

m4 <- lm(PostGFProtestCount ~ population + BlackPopPct + BlackPovRate + EduRate + VictimsPreGF2020, data = ProtestByCity)
nobs(m4) #15388 # drops places with no Black People
used_data <- model.frame(m4)
dropped_obs <- anti_join(ProtestByCity, used_data, by = c("PostGFProtestCount","population"))
summary(m4)

m5 <- lm(PostGFProtestCount ~ population + BlackPopPct + BlackPovRate + EduRate + BlackVictimCountPreGF, data = ProtestByCity)
nobs(m5) #15388
summary(m5)

m6 <- lm(PostGFProtestCount ~ population + BlackPopPct + BlackPovRate + EduRate + BlackVictimCountPreGF, data = ProtestByCity)
nobs(m6) #15388
summary(m6)

m7 <- lm(PostGFProtestCount ~ population + BlackPopPct + BlackPovRate + EduRate + AntiTrumpProtestPreGFCount + BlackVictimCountPreGF, data = ProtestByCity)
nobs(m7) #15388
summary(m7) #controling for anti-trump protests makes the education rate go negative. 

m15 <- lm(PostGFProtestCount ~ population + BlackPopPct + BlackPovRate + EduRate + BlackVictimCountPreGF, data = ProtestByCity)
nobs(m15) #15388
summary(m15)


ProtestByCity$PoliceDeathsRate <- ProtestByCity$VictimCountPreGF/ProtestByCity$population
ProtestByCity$BlackVictimsRate <- ProtestByCity$BlackVictimCountPreGF/ProtestByCity$population

m16 <- lm(PostGFProtestCount ~ population + BlackPopPct + BlackPovRate + EduRate + PoliceDeathsRate, data = ProtestByCity)
nobs(m16) #15388
summary(m16)

```

## Scatter Plots

### Scatter Plot of Protest Count vs. Police Deaths Rate


```{r scatter 1}
p1 <- ggplot(ProtestByCity, aes(x = PoliceDeathsRate, y = PostGFProtestCount)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = TRUE, color = "blue") +
  labs(title = "Post-GF Protest Count vs. Police Deaths Rate",
       x = "Police Deaths Rate (Victims per capita)",
       y = "Post-GF Protest Count") +
  theme_minimal()
p1
```

### Post-GF Protest Count vs. Black Victims

```{r scatter 2}
p1 <- ggplot(ProtestByCity, aes(x = BlackVictimCountPreGF, y = PostGFProtestCount)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = TRUE, color = "blue") +
  labs(title = "Scatter Plot of Post-GF Protest Count vs. Black Victims Prior to GF Death",
       x = "Black Victims of Police Violence ",
       y = "Post-GF Protest Count") +
  theme_minimal()
p1
```

### Post-GF Protest Count vs. Victims Count

```{r scatter 3}

p2 <- ggplot(ProtestByCity, aes(x = VictimsCount, y = PostGFProtestCount)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = TRUE, color = "blue") +
  labs(title = "Scatter Plot of Post-GF Protest Count vs. Police Deaths Rate",
       x = "Black Victims of Police Violence ",
       y = "Post-GF Protest Count") +
  theme_minimal()
p2
```

### Post-GF Protest Count vs. Anti-Trump Protest Count

```{r scatter 4}

p3 <- ggplot(ProtestByCity, aes(x = AntiTrumpProtestPreGFCount, y = PostGFProtestCount)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = TRUE, color = "blue") +
  labs(title = "Scatter Plot of Post-GF Protest Count vs. Police Deaths Rate",
       x = "Anti Trump PRotest Count ",
       y = "Post-GF Protest Count") +
  theme_minimal()
p3
```

